config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { 
    registrations: 'registrations', 
    omniauth_callbacks: 'callbacks' }

  root 'welcome#index'

  resources :users, :only => [:show, :index, :edit]

    resources :contacts, :only => [:index, :new, :create, :show, :edit, :update, :destroy]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :reminders
	belongs_to :user
	has_many :emails

	validates(:name, :presence => true)

	
  end

app/models/email.rb
class Email < ActiveRecord::Base
	belongs_to :contact

	


end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
	belongs_to :contact
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :contacts, dependent: :destroy
  has_many :reminders, through: :contacts
  after_create :send_sign_up_email

  def self.from_omniauth(auth)

    user = where(provider: auth.provider, uid: auth.uid).first_or_initialize
    user.name = auth.info.name
    user.email = auth.info.email

    # unless the user was already created
    unless user.persisted?
      random_password = Devise.friendly_token[0,20]
      user.password = random_password
      user.password_confirmation = random_password
    end
    
    user.save!
    user
  end    


  protected

  def send_sign_up_email
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :load_contacts, :only => [:index, :show, :create]
  before_action :load_new_contact, :only => [:index, :new]
  before_action :authenticate_user!
  
  def index

  end

  def new
  end

  def show 
    @contact = Contact.find(params[:id])
    @emails = @contact.emails

  end


  def create

    @contact = Contact.new(contact_params)
    if @contact.save
      if !params["reminder"].nil?
        if params["reminder"].include? "1"
          @reminder = Reminder.new(:contact_id => @contact.id, :date => (Date.today + 1.week))
          @reminder.save
        end
        if params["reminder"].include? "2"
          @reminder = Reminder.new(:contact_id => @contact.id, :date => (Date.today + 1.month))
          @reminder.save
        end
        if params["reminder"].include? "3"
          @reminder = Reminder.new(:contact_id => @contact.id, :date => (Date.today + 3.months))
          @reminder.save
        end
        if params["reminder"].include? "4"
         @reminder = Reminder.new(:contact_id => @contact.id, :date => (Date.today + 6.months))
         @reminder.save
        end
      end
      redirect_to user_path(current_user)
   else
    render :index
  end
end

def edit
  @contact = Contact.find(params[:id])
end

def update
  @contact = Contact.find(params[:id])
  @contact.update_attributes(contact_params)
  @contact.reminders.each do |reminder|
    reminder.destroy
  end
  if !params["reminder"].nil?
    if params["reminder"].include? "1"
        @reminder = Reminder.new(:contact_id => @contact.id, :date => (Date.today + 1.week))
        @reminder.save
    end
    if params["reminder"].include? "2"
      @reminder = Reminder.new(:contact_id => @contact.id, :date => (Date.today + 1.month))
      @reminder.save
    end
    if params["reminder"].include? "3"
      @reminder = Reminder.new(:contact_id => @contact.id, :date => (Date.today + 3.months))
      @reminder.save
    end
    if params["reminder"].include? "4"
     @reminder = Reminder.new(:contact_id => @contact.id, :date => (Date.today + 6.months))
     @reminder.save
    end
  end
  redirect_to contact_path
end

def destroy
  @contact = Contact.find(params[:id])
  @contact.destroy

  flash[:notice] = "Your contact was deleted successfully."

  redirect_to user_path(current_user)
end



private

def contact_params
  params["contact"].permit(:name, :email, :company, :notes, :reminder, :reminder_date, :reminder_date_2, :reminder_date_3, :reminder_date_4).merge(:user => current_user)
end

def load_new_contact
  @contact = Contact.new
end

def load_contacts
  @contacts = current_user.contacts
end

end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

		
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  protected

  # my custom fields are :name, :heard_how
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, 
        :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :current_password,
        :email, :password, :password_confirmation)
    end
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end
  


end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :authenticate_user!
    before_action :user_signed_in?

  	def show
   		 @user = current_user
   		 @contact = Contact.new
   		 @contacts = @user.contacts
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if user_signed_in?
			redirect_to user_path(current_user)
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_action?(controller_name, action_name)
		controller.controller_name == controller_name && controller.action_name == action_name
	end

	def resource_name
   :user
 end

 def resource_class
  devise_mapping.to
end

def resource
 @resource ||= User.new
end

def devise_mapping
 @devise_mapping ||= Devise.mappings[:user]
end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_alerts.html.erb
<% if false %>
<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>
<% end %>

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <a class="navbar-brand" href="/" style="position: relative; z-index: 2"; ><img src="/assets/networker_logo_thumb.png" style="margin-bottom: 10px; display: block; margin-left: auto; margin-right: auto;"></a>

    <p class="navbar-text" style="position: absolute; left: 0; width: 100%; text-align: center; z-index: 1;">[networker]</p>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Add Contact<span class="sr-only">(current)</span></a></li>
        <li><a href="#">Add Contact</a></li>
      </ul> -->
      <!-- <div class="navbar-text" style="width: 36%"></div> -->
      
      <ul class="nav navbar-nav navbar-right" style="position: relative; z-index: 2;">
        <li><%= link_to 'About Us', new_contact_path %></li>
        <li class="dropdown" style="position: relative; z-index: 2">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to 'Edit Profile', edit_user_registration_path %></li>
            <!-- <li><a href="#">Sign Out</a></li>
            <li><a href="#">Something else here</a></li> -->
            <li role="separator" class="divider"></li>
            <li><%=link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/contacts/_contact.html.erb
<tr>
  <td>
    <div class="contact_name">
     <%= link_to contact.name, contact_path(contact.id) %>
    </div>

  </td>
</tr>

app/views/contacts/_emails.html.erb
<div id="accordion">
	<% @emails.each do |e| %>
		<h3> <b> Subject: </b><%=e.subject%> <b> Sent: </b> <%= time_ago_in_words(e.date) %> ago </h3>
		<div><p><%=	e.body %></p></div>
	<% end %> 
</div>
<script>
  $(function() {
    $( "#accordion" ).accordion({
      collapsible: true
    });
  });
</script>

app/views/contacts/_errors.html.erb
<% if contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

    <ul>
    <% contact.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<%= form_for(contact, {:url => "/contacts", :html => {:class => 'contact_form'}}) do |f| %>
  <%= f.text_field :name, :placeholder => "Name", class:"form-control" %> <br>
  <%= f.text_field :email, :placeholder => "Email", class:"form-control" %> <br>
  <%= f.text_field :company, :placeholder => "Company", class:"form-control" %> <br>
  <%= f.text_area :notes, :placeholder => "Notes (jot down some interesting tidbits you learned about this contact)", class:"form-control" %> <br>

<div class="row">
  <div class="col-sm-12">
    <div class="input-group">
      <span class="input-group-addon">
        <input type="checkbox" value="1" name="reminder[]">
      </span>
      <input type="text" class="form-control" value="Remind me in a week" aria-label="..." readonly>
    </div><!-- /input-group -->
    <div class="input-group">
      <span class="input-group-addon">
        <input type="checkbox" value="2" name="reminder[]">
      </span>
      <input type="text" class="form-control" value="Remind me in a month" aria-label="..." readonly>
    </div><!-- /input-group -->
    <div class="input-group">
      <span class="input-group-addon">
        <input type="checkbox" value="3" name="reminder[]">
      </span>
      <input type="text" class="form-control" value="Remind me in three months" aria-label="..." readonly>
    </div><!-- /input-group -->
    <div class="input-group">
      <span class="input-group-addon">
        <input type="checkbox" value="4" name="reminder[]">
      </span>
      <input type="text" class="form-control" value="Remind me in six months" aria-label="..." readonly>
    </div><!-- /input-group -->
  </div>
</div>

<!--   <select name="contact[reminder]">
  <option value="" selected="selected">When would like to be reminded?</option>
  <option value="1">1 week</option>
  <option value="2">1 month</option>
  <option value="3">3 months</option>  -->

<%= f.submit :class => 'form-control' %>
<% end %>

app/views/contacts/_template.html.erb
<!DOCTYPE html>
<html>

<body>

<textarea class="email-template" rows="10" id='fe_text' cols="75"> 
Dear <%=contact.name%>,

It's been a while since we last talked, and I just wanted to check in to see how **INSERT PERSONAL INFO HERE** is going.

*** USE YOUR NOTES TO ASK THIS CONTACT ABOUT THEIR LIFE ***

Can't wait to hear from you again!

Best regards,
<%=contact.user.name%>
</textarea><br/>
<button class='my_clip_button' data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button' title='Click me to copy to clipboard.'>
    Copy To Clipboard...
  </button>
<a href="https://mail.google.com/mail/u/0/#inbox?compose=new" target="_blank"><button>Send Email</button></a>

</body>

<script>
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });
</script>

</html>

app/views/contacts/edit.html.erb
 <%= form_for(@contact) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :company %>
      <%= f.text_field :company, class: 'form-control' %>

      <%= f.label :notes %>
      <%= f.text_field :notes, class: 'form-control' %>

<!-- TODO: just copy,pasted this code in from the _form file. need to link it to add an upcoming reminder -->

<div class="row">
  <div class="col-sm-6">
    <div class="input-group">
      <span class="input-group-addon">
        <input type="checkbox" value="1" name="reminder[]">
      </span>
      <input type="text" class="form-control" value="Remind me in a week" aria-label="..." readonly>
    </div><!-- /input-group -->
    <div class="input-group">
      <span class="input-group-addon">
        <input type="checkbox" value="2" name="reminder[]">
      </span>
      <input type="text" class="form-control" value="Remind me in a month" aria-label="..." readonly>
    </div><!-- /input-group -->
    <div class="input-group">
      <span class="input-group-addon">
        <input type="checkbox" value="3" name="reminder[]">
      </span>
      <input type="text" class="form-control" value="Remind me in three months" aria-label="..." readonly>
    </div><!-- /input-group -->
    <div class="input-group">
      <span class="input-group-addon">
        <input type="checkbox" value="4" name="reminder[]">
      </span>
      <input type="text" class="form-control" value="Remind me in six months" aria-label="..." readonly>
    </div><!-- /input-group -->
  </div>
</div>


      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

app/views/contacts/index.html.erb
<%= render :partial => 'errors', :locals => {:contact => @contact} %>

<br/><br/>

<div class="new_contact_wrapper">
<%= render :partial => 'form', :locals => {:contact => @contact} %>
</div>

<table class="contacts_list">
<% @contacts.each do |contact| %>
  <%= render partial: "contact", locals: {contact: contact} %>
<% end %>
</table>

app/views/contacts/new.html.erb
<%= render :partial => 'contacts/form', :locals => {:contact => @contact} %>

app/views/contacts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">

        <!-- <h2> <%=@contact.name%> </h2>

        <%=link_to 'Edit Contact', edit_contact_path %>
        | <%=link_to 'Delete Contact', "/contacts/#{@contact.id}", :method => :delete %> -->

      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading contact-page-person-heading"><h2><%="[#{@contact.name.downcase}]"%> <br> <%= image_tag("networker_logo_thumb2.png")%></h2> 
        </div> 
        <div class="panel-body">
        <p><b>Company: </b><%= "#{@contact.company}" %> | <b>Email: </b> <%= "#{@contact.email}" %></p>
        <%=link_to 'Edit Contact', edit_contact_path %>
        | <%=link_to 'Delete Contact', "/contacts/#{@contact.id}", :method => :delete %>
        </div>
        <!-- TODO: put in rest of contact info here, i.e. company, email, etc -->

      </div>
      </div>
      <div class ="col-sm-2"></div>
      <div class ="col-sm-6">

      <!-- List group -->
        <ul class="list-group">
        <li class="list-group-item"><h2>Reminders:</h2></li>
        <% @contact.reminders.each do |reminder| %>
        <li class="list-group-item"><%= reminder.date.strftime("%A, %b %e %Y") %></li>
        <% end %>
        </ul>

      </div>

    </div> <!-- closes col-sm-4 -->
    <br> <br> 
<% if !(@contact.emails.nil?) %>
    <h2> Notes </h2>
    <% end %>
  <div class="row">
    <div class="col-sm-6">
      <%= render partial: "emails", locals: {contact: @contact, emails: @emails}  %>
    </div>
    <div class="col-sm-6">
      <%= render partial: "template", locals: {contact: @contact} %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Touch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<% body_class = "" %>
<% body_class = "home-page" if current_action?('users', 'show') %>
<% body_class = "contacts-page" if current_action?('contacts', 'show') %>

<body class="<%= body_class %>">

  <% if user_signed_in? %>
    <%= render partial: "nav" %>
  <div class="layer"></div>
  <%end%>

  <div id="container">
    <!-- TODO: comment these out before we demo because they look like shit and we don't need them except for error checking -->
    <%= render partial: "alerts" %>
    <% if false %>
      <% if user_signed_in? %>
      Signed in as <%=current_user.name%> | 
      <%=link_to 'Sign Out', destroy_user_session_path, :method => :delete %> | <%=link_to 'Edit Profile', edit_user_registration_path %>
      <% else %>
      <% end %>

      <% if !current_page?(root_path) && user_signed_in? %>
      | <%=link_to 'Home Page', root_path %>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_contacts.html.erb
<!-- TODO: make the headers not scroll with the options -->
<div class="panel panel-default contact-panel">
  <!-- Default panel contents -->
  <div class="panel-heading contact-heading"><h2>Contacts</h2></div>

  <!-- List group -->
  <ul class="list-group">
	<% @contacts.each do |contact| %>
    <li class="list-group-item contacts-list"><b><%= link_to ("#{contact.name} (#{contact.company})"), contact_path(contact.id) %></b></li>
    <% end %>
  </ul>
  </div>

app/views/users/_reminders.html.erb
<!-- TODO: make the headers not scroll with the options -->
<div class="panel panel-default reminder-panel">
  <!-- Default panel contents -->
  <div class="panel-heading reminders_heading"><h2>Upcoming Reminders</h2></div>

  <!-- List group -->
  <ul class="list-group">
  <% @user.reminders.order(:date).each do |reminder| %>
    <li class="list-group-item reminders-list"><b><%= "#{Contact.find(reminder.contact_id).name} on #{reminder.date.strftime("%A, %B %e, %Y")}"  %></b></li>
    <% end %>
  </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<%= render :partial => '/users/contacts', :locals => {:contact => @contact} %>
			<!-- puts "upcoming reminders" in same row -->
		</div>
		<div class="col-sm-4">
			<button class="btn add-contact-button" type="button" data-toggle="collapse" data-target="#collapseform" aria-expanded="false" aria-controls="collapseform">
				<h2>Add Contact <b>+</b></h2>
			</button>
			<div class="collapse" id="collapseform">
				<div class="well">
					<%= render :partial => 'contacts/form', :locals => {:contact => @contact} %>
				</div>
			</div>

			
		</div>
		<div class="col-sm-4">
			<%= render :partial => '/users/reminders', :locals => {:contact => @contact} %>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<video autoplay muted id="bgvid">
<source src="<%= image_path("networker_video.mp4") %>" type="video/mp4">
</video>
<div class="container" style="display: none;">
	<div class="business_card">
		<div class="center">
			<div class="networker"> 
				[networker] 
			</div>
			<div class="suit_icon">
				<%= image_tag("networker_logo1.png", {alt: "NETWORKER"}) %>
			</div>
			<%= render file: "devise/sessions/new" %>
		</div>
	</div>
</div>

<script type="text/javascript">
	setTimeout(function(){ $('.container').fadeIn(1000); }, 6000);
</script>